### ISSUE TITLE
errors then create data

### ISSUE THREAD

**Issue by TianhaoFu** [Gorilla-Lab-SCUT/VISTA#10]
hi when i run the 
`python tools/create_data.py nuscenes_data_prep --root_path="data/nuScenes/" --version="v1.0-trainval" --nsweeps=10`
command, i came across such error:
```
Traceback (most recent call last):
  File "tools/create_data.py", line 106, in <module>
    fire.Fire()
  File "/opt/conda/lib/python3.6/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/opt/conda/lib/python3.6/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "tools/create_data.py", line 89, in nuscenes_data_prep
    resample_infos(train_info_copy_path, val_info_copy_path, nsweeps)
  File "tools/create_data.py", line 67, in resample_infos
    new_train_info_path = train_info_path.replace('velo.pkl', 'velo_resampled.pkl')
TypeError: replace() takes 2 positional arguments but 3 were given
```

could you helps me ?

thanks!

**Comment by AndlollipopDE** [comment]
The train_info_path is a Path variable, it should be an str variable, the bug should be fixed after a new push now
