### ISSUE TITLE
problem when evaluate the nuscenes dataset-mini  in colab

### ISSUE THREAD

**Issue by RouDanCongJii** [Gorilla-Lab-SCUT/VISTA#15]
hallo,
when i evaluate the minidataset with the cmd
`!./tools/scripts/test.sh /content/VISTA/configs/vista/vista.py /content/VISTA/checkpoint  --eval bbox`
 there is an error 

`Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "./tools/dist_test.py", line 186, in <module>
    main()
  File "./tools/dist_test.py", line 86, in main
    torch.cuda.set_device(args.local_rank)
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 261, in set_device
    torch._C._cuda_setDevice(device)
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
Traceback (most recent call last):
  File "./tools/dist_test.py", line 186, in <module>
    main()
  File "./tools/dist_test.py", line 86, in main
    torch.cuda.set_device(args.local_rank)
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 261, in set_device
    torch._C._cuda_setDevice(device)
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
Traceback (most recent call last):
  File "./tools/dist_test.py", line 186, in <module>
    main()
  File "./tools/dist_test.py", line 86, in main
    torch.cuda.set_device(args.local_rank)
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 261, in set_device
    torch._C._cuda_setDevice(device)
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
Traceback (most recent call last):
  File "./tools/dist_test.py", line 186, in <module>
    main()
  File "./tools/dist_test.py", line 86, in main
    torch.cuda.set_device(args.local_rank)
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 261, in set_device
    torch._C._cuda_setDevice(device)
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
Killing subprocess 3601
Killing subprocess 3602
Killing subprocess 3603
Killing subprocess 3604
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/usr/local/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-u', './tools/dist_test.py', '--local_rank=3', '/content/VISTA/configs/vista/vista.py', '--work_dir=/content/VISTA/checkpoint', '--checkpoint=--eval', '--test', 'True']' returned non-zero exit status 1.`

Wed Jul 27 08:29:44 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P0    25W / 250W |      2MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |

and  another problem
when i create the data 
`!python tools/create_data.py nuscenes_data_prep --root_path=NUSCENES_TRAINVAL_DATASET_ROOT --version="v1.0-mini" --nsweeps=10`
there is an erroe
`ModuleNotFoundError: No module named 'det3d.datasets.kitti' `

thanks

**Comment by Verneinender** [comment]
> ModuleNotFoundError: No module named 'det3d.datasets.kitti'

You can just comment out  `from .kitti import KittiDataset` and similar parts.
