### ISSUE TITLE
How can I train on nuscenes v1.0-mini?

### ISSUE THREAD

**Issue by zheng0819** [Gorilla-Lab-SCUT/VISTA#19]
The memory of my computer is not enough to train on nuscenes v1.0, so I try to train on nuscenes v1.0-mini. I change the config file, but an error occurred while training :
Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yusen0819/anaconda3/envs/vista/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yusen0819/anaconda3/envs/vista/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yusen0819/anaconda3/envs/vista/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yusen0819/VISTA/det3d/datasets/nuscenes/nuscenes.py", line 193, in __getitem__
    return self.get_sensor_data(idx)
  File "/home/yusen0819/VISTA/det3d/datasets/nuscenes/nuscenes.py", line 189, in get_sensor_data
    data, _ = self.pipeline(res, info)
  File "/home/yusen0819/VISTA/det3d/datasets/pipelines/compose.py", line 25, in __call__
    res, info = t(res, info)
  File "/home/yusen0819/VISTA/det3d/datasets/pipelines/preprocess.py", line 96, in __call__
    gt_drop_max_keep=self.gt_drop_max_keep,
  File "/home/yusen0819/VISTA/det3d/core/sampler/sample_ops.py", line 247, in sample_all
    "points": np.concatenate(s_points_list, axis=0),
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
  File "/home/yusen0819/VISTA/det3d/torchie/trainer/trainer.py", line 389, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/yusen0819/VISTA/det3d/torchie/trainer/trainer.py", line 542, in run
    epoch_runner(data_loaders[i], self.epoch, **kwargs)
  File "/home/yusen0819/VISTA/det3d/torchie/apis/train.py", line 336, in train_detector
    trainer.run(data_loaders, cfg.workflow, cfg.total_epochs, local_rank=cfg.local_rank)
  File "/home/yusen0819/VISTA/tools/train.py", line 126, in main
    logger=logger,
  File "/home/yusen0819/VISTA/tools/train.py", line 131, in <module>
    main()
I cannot handle this error. How can I train on nuscenes v1.0-mini? Thanks.

**Comment by AndlollipopDE** [comment]
We have not tried to train on the mini version, but the error messages indicate that you may not generate data properly (the database sampling).
