### ISSUE TITLE
ModuleNotFoundError: No module named 'det3d.utils.dist'

### ISSUE THREAD

**Issue by XGP810364691** [Gorilla-Lab-SCUT/VISTA#3]
I'm debugging your code and running "python tools/create_data.py nuscenes_data_prep --root_path=NUSCENES_TRAINVAL_DATASET_ROOT --version="v1.0-trainval" --nsweeps=10" this code. The following error occurs

(vista) xgp@xgp-pc:~/pyPrj/VISTA$ python tools/create_data.py nuscenes_data_prep --root_path=NUSCENES_TRAINVAL_DATASET_ROOT --version="v1.0-trainval" --nsweeps=10
Traceback (most recent call last):
  File "tools/create_data.py", line 11, in <module>
    from det3d.datasets.nuscenes import nusc_common as nu_ds
  File "/home/xgp/pyPrj/VISTA/det3d/datasets/__init__.py", line 3, in <module>
    from .nuscenes import NuScenesDataset
  File "/home/xgp/pyPrj/VISTA/det3d/datasets/nuscenes/__init__.py", line 1, in <module>
    from .nuscenes import NuScenesDataset
  File "/home/xgp/pyPrj/VISTA/det3d/datasets/nuscenes/nuscenes.py", line 15, in <module>
    from det3d.datasets.custom import PointCloudDataset
  File "/home/xgp/pyPrj/VISTA/det3d/datasets/custom.py", line 8, in <module>
    from .pipelines import Compose
  File "/home/xgp/pyPrj/VISTA/det3d/datasets/pipelines/__init__.py", line 16, in <module>
    from .preprocess import Preprocess, Voxelization
  File "/home/xgp/pyPrj/VISTA/det3d/datasets/pipelines/preprocess.py", line 6, in <module>
    from det3d.builder import (
  File "/home/xgp/pyPrj/VISTA/det3d/builder.py", line 18, in <module>
    from det3d.models.losses import losses
  File "/home/xgp/pyPrj/VISTA/det3d/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/xgp/pyPrj/VISTA/det3d/models/backbones/__init__.py", line 1, in <module>
    from .scn import RCNNSpMiddleFHD, SpMiddleFHD
  File "/home/xgp/pyPrj/VISTA/det3d/models/backbones/scn.py", line 8, in <module>
    from det3d.models.utils import Empty, change_default_args
  File "/home/xgp/pyPrj/VISTA/det3d/models/utils/__init__.py", line 1, in <module>
    from .conv_module import ConvModule, build_conv_layer
  File "/home/xgp/pyPrj/VISTA/det3d/models/utils/conv_module.py", line 7, in <module>
    from .norm import build_norm_layer
  File "/home/xgp/pyPrj/VISTA/det3d/models/utils/norm.py", line 4, in <module>
    from det3d.utils.dist import dist_common as comm
ModuleNotFoundError: No module named 'det3d.utils.dist'

Can you help me solve this problem? thank you

**Comment by AndlollipopDE** [comment]
Thanks for asking, I push the codes, please fetch the new commits.

**Comment by XGP810364691** [comment]
来信已收到，谢谢徐广鹏
